### ISSUE TITLE
Update catrige on openshift

### ISSUE THREAD

**Issue by nhymxu** [getupcloud/openshift-nginx-php-fpm#1]
Sorry, It's question, not issus about your catrige.

I want ask about update catrige.

Exam: You push v1 to github. I create catrige with your code on openshift.
After some month, you update something, push v2 to github.

How to upgrade my running catrige to v2?

thanks!

**Comment by caruccio** [comment]
Hi.
Upgrades are handled in two ways:

1 - Cartridge code itself (startup scripts, default configs, manifest.yml, etc)
This is updated by us (openshift mantainers), since users can't overwrite those files. This is a transparent process and should not create any issue. As soon as we create v2, it will be updated on openshift.

2 - Your code and config (files from dir config/*). Those are user owned files, so you need only to update locally and push it to your app.

**Comment by nhymxu** [comment]
hmm, upgrade I talk about is: current v1 run with PHP 5.4.1
I installed it.
You update git repo to v1.1 with PHP 5.4.2

How to update on my openshift?
Manual by me or need openshift system?

sorry for my english

**Comment by caruccio** [comment]
Patch level upgrades (5.4.x) are done by upgrading your rpm package for php module. If you use scl for php packages, simply upgrade your rpms and it is done. All users need to do is to restart its apps so they start with new module.

This cartridge sets on minor versions (5.x) as you can see here https://github.com/getupcloud/openshift-nginx-php-fpm/blob/master/metadata/manifest.yml#L6

**Comment by nhymxu** [comment]
I try install with your cartridge. But alway install PHP 5.3 :(

**Comment by caruccio** [comment]
To select versions the cartridge must be installed in your openshift, or you could use parameter `v`, but this is an unofficial feature:

```
rhc app create phpfpm https://reflector-getupcloud.getup.io/reflect?github=getupcloud/openshift-nginx-php-fpm&v=5.4
```

**Comment by ewwink** [comment]
it used nginx 1.0.15 how to update to   nginx 1.5.8 ?

**Comment by caruccio** [comment]
You need to fork the repo, re-compile nginx from source (or extract binary from rpm) and overwrite files inside `versions/shared/usr/*`. Also, keep an eye on config files from `versions/shared/configuration/etc` since there may be critic changes because nginx versions are to distant.

**Comment by ewwink** [comment]
thanks I will try.

**Comment by ewwink** [comment]
Hooray... I can update it to nginx 1.5.9 and php 5.4 https://github.com/ewwink/openshift-nginx-php-fpm but I can't run with php 5.5 `Failed to execute: 'control start'....php-fpm`

@caruccio thanks for your support

**Comment by caruccio** [comment]
Cool! I'll take a look at it ASAP.

**Comment by caruccio** [comment]
Regarding PHP 5.5, if you are running it at openshift online (from redhat), they don't have PHP 5.4 support yet. Only 5.4.

You could try it on getupcloud.com. There is a 750h free trial.
