### ISSUE TITLE
Error establishing a database connection

### ISSUE THREAD

**Issue by ranib** [getupcloud/openshift-nginx-php-fpm#12]
I'm very close to have a working wordpress install for nginx in openshift. Let me explain how I reached here.

Installed nginx cartridge using https://github.com/pinodex/openshift-nginx-php-fpm and mysql-5.5 by creating a new app. Added remote upstream https://github.com/ranib/wordpress-example.git & pull
Edited 'deploy' in action_hooks then commit & push - and it installed wordpress successfully.
Visiting app's url gives me "Error establishing a database connection" error message.
SFTP into gear and remove wp-config file and tried again app's url
Now I get "Create a configuration file" and installs wordpress by using mysql database credentials provided by openshift at the time of mysql install.

This means getenv variables listed below for wp-config are not working

/*\* The name of the database for WordPress */
define('DB_NAME', getenv('OPENSHIFT_APP_NAME'));

/*\* MySQL database username */
define('DB_USER', getenv('OPENSHIFT_MYSQL_DB_USERNAME'));

/*\* MySQL database password */
define('DB_PASSWORD', getenv('OPENSHIFT_MYSQL_DB_PASSWORD'));

/*\* MySQL hostname */
define('DB_HOST', getenv('OPENSHIFT_MYSQL_DB_HOST') . ':' . getenv('OPENSHIFT_MYSQL_DB_PORT'));

while it works with define('DB_NAME', 'actual-mysql-db-name'); likewise for username, password and hostname variable which is not a good option in openshift. I know I need to tweak wp-config file of openshift/wordpress-example to work with nginx. I'm hoping experts here will guide me in the right direction.

I added phpinfo.php file in Apache and Nginx server and found that Mysql getenv variables required for wp-config were not found in Nginx server while they were available in Apache server. I'm sure this will ring a bell for experts here that can help.I'm very close to have a working wordpress install for nginx in openshift. Let me explain how I reached here.

**Comment by caruccio** [comment]
Hi there. Looks like nginx is not exporting OPENSHIFT_\* variables to php-fpm. This is due to a restriction applied in file `config/nginx.d/export_env.erb` from your app repo.
Edit it and change line 3 from:

```
 puts "fastcgi_param #{name} '#{value}';" unless name.start_with?("OPENSHIFT_");
```

to:

```
 puts "fastcgi_param #{name} '#{value}';";
```

Please let me known if it worked ;)

**Comment by ranib** [comment]
Thanks, bparees from https://github.com/openshift/wordpress-example/issues/61 also suggest the same. He said "For apache, we have to explicitly expose the env variables via the apache config PassEnv to ensure they are visible in php, perhaps something similar is needed in nginx".

I made the change as you suggested, but that did NOT work. Can you think of anything else?

**Comment by ranib** [comment]
Good luck for your Soccer game today with Mexico.

FYI, I also tried as I commented in this thread today https://github.com/openshift/wordpress-example/issues/61 and it did NOT work.
