### ISSUE TITLE
libpcre not found while creating app

### ISSUE THREAD

**Issue by sebasmagri** [getupcloud/openshift-nginx-php-fpm#15]
I'm getting the following error while trying to use this cartridge:

```
/var/lib/openshift/53b60b0765fe3fcaa3000010/nginx-php-fpm//usr/sbin/nginx: error while loading shared libraries: libpcre.so.0: cannot open shared object file: No such file or directory
```

**Comment by getupcloud** [comment]
Hi. Looks like it's the same problem as
https://github.com/getupcloud/openshift-nginx-php-fpm/issues/5

_Mateus Caruccio_Master of Puppets+55 (51) 8298.0026gtalk:

_mateus.caruccio@getupcloud.com diogo.goebel@getupcloud.comtwitter:
@MateusCaruccio https://twitter.com/MateusCaruccio_This message and any
attachment are solely for the intended
recipient and may contain confidential or privileged information
and it can not be forwarded or shared without permission.
Thank you!

**Comment by sebasmagri** [comment]
Oh didn't check the contents of the issue. Will check the workarounds there and close this as duplicate.

Thanks!
