### ISSUE TITLE
I am not able to deploy nginx using this Cartrage.

### ISSUE THREAD

**Issue by erfan-ilyas** [getupcloud/openshift-nginx-php-fpm#16]
I don't know if its only me.
I am trying to deploy this cartridge but i am getting this error:

Creating application 'phpfpm' ...
Building nginx configuration
Building php-fpm configuration
Failed to execute: 'control start' for
/var/lib/openshift/5460e2eee0b8cd9b04000200/nginx-php-fpm

But i can install and deploy other cartridges:
for example:
https://github.com/tengyifei/openshift-cartridge-nginx-hhvm

Can anybody help?

**Comment by caruccio** [comment]
I've just added a new var NGINX_PHP_FPM_DEBUG so you can see what is happening during start.
Just add `NGINX_PHP_FPM_DEBUG=1` to your `rhc app create` command and paste the results here.

**Comment by erfan-ilyas** [comment]
This the output i am getting.

Cartridges:            https://reflector-getupcloud.getup.io/reflect?github=getu
pcloud/openshift-nginx-php-fpm
Gear Size:             default
Scaling:               no
Environment Variables: NGINX_PHP_FPM_DEBUG=1

Creating application 'phpfpm' ...
Building nginx configuration
Building php-fpm configuration
Failed to execute: 'control start' for
/var/lib/openshift/5460e8bd500446ca060003e8/nginx-php-fpm
+
NGINX_CFG_FILE=/var/lib/openshift/5460e8bd500446ca060003e8/nginx-php-fpm//config
uration/etc/nginx.conf
+
NGINX_PID_FILE=/var/lib/openshift/5460e8bd500446ca060003e8/nginx-php-fpm//run/ng
inx.pid
+
PHP_CFG_FILE=/var/lib/openshift/5460e8bd500446ca060003e8/nginx-php-fpm//configur
ation/etc/php-fpm.conf
+
PHP_PID_FILE=/var/lib/openshift/5460e8bd500446ca060003e8/nginx-php-fpm//run/php-
fpm.pid
- case "$1" in
- start
- build_nginx_config
- echo Building nginx configuration
- _run_template
  /var/lib/openshift/5460e8bd500446ca060003e8/app-root/runtime/repo//config/nginx.
  d/default.conf.erb
  /var/lib/openshift/5460e8bd500446ca060003e8/app-root/runtime/repo//config/nginx.
  d/export_env.erb
- for conf in '$@'
- '[' -e
  /var/lib/openshift/5460e8bd500446ca060003e8/app-root/runtime/repo//config/nginx.
  d/default.conf.erb
  ']'
- /usr/bin/oo-erb
  /var/lib/openshift/5460e8bd500446ca060003e8/app-root/runtime/repo//config/nginx.
  d/default.conf.erb
- for conf in '$@'
- '[' -e
  /var/lib/openshift/5460e8bd500446ca060003e8/app-root/runtime/repo//config/nginx.
  d/export_env.erb
  ']'
- /usr/bin/oo-erb
  /var/lib/openshift/5460e8bd500446ca060003e8/app-root/runtime/repo//config/nginx.
  d/export_env.erb
- build_phpfpm_config
- echo Building php-fpm configuration
- _run_template
  /var/lib/openshift/5460e8bd500446ca060003e8/app-root/runtime/repo//config/php-fp
  m.d/export_env.conf.erb
- for conf in '$@'
- '[' -e
  /var/lib/openshift/5460e8bd500446ca060003e8/app-root/runtime/repo//config/php-fp
  m.d/export_env.conf.erb
  ']'
- /usr/bin/oo-erb
  /var/lib/openshift/5460e8bd500446ca060003e8/app-root/runtime/repo//config/php-fp
  m.d/export_env.conf.erb
- _start_php
- _php-fpm -D -y
  /var/lib/openshift/5460e8bd500446ca060003e8/nginx-php-fpm//configuration/etc/php
  -fpm.conf

**Comment by erfan-ilyas** [comment]
I was able to resolve the issue by modifying the following file:

/ usr / template / config / php-fpm.d / export_env.conf.erb

Original code was:
<%
ENV.each do |name, value|
puts "env[#{name}] = #{value}";
end
%>

This file was producing empty LANG value, So i hard-coded this to add "en" value.
I am not sure why it is empty now? 

Here is the working code for me:

<%
ENV.each do |name, value|
    if name == "LANG"
        puts "env[LANG] = en";
    else
        puts "env[#{name}] = #{value}";
    end
end
%>

Thanks.

**Comment by caruccio** [comment]
As we say here in Brazil: you just hit the fly ;)

```
+ /usr/bin/scl enable php54 'php-fpm -D -y /var/lib/openshift/5460ff7a5004467cff00006b/nginx-php-fpm//configuration/etc/php-fpm.conf'
[10-Nov-2014 13:10:37] ERROR: [/var/lib/openshift/5460ff7a5004467cff00006b/app-root/runtime/repo//config/php-fpm.d/export_env.conf:31] empty value
[10-Nov-2014 13:10:37] ERROR: Unable to include /var/lib/openshift/5460ff7a5004467cff00006b/app-root/runtime/repo//config/php-fpm.d/export_env.conf from /var/lib/openshift/5460ff7a5004467cff00006b/nginx-php-fpm//configuration/etc/php-fpm.conf at line 31
[10-Nov-2014 13:10:37] ERROR: failed to load configuration file' /var/lib/openshift/5460ff7a5004467cff00006b/nginx-php-fpm//configuration/etc/php-fpm.conf'
[10-Nov-2014 13:10:37] ERROR: FPM initialization failed
```

It's [fixed now](https://github.com/getupcloud/openshift-nginx-php-fpm/commit/4c8a581373aafc93c32933fa58e89c557f7fd437).
Thanks!
