### ISSUE TITLE
Update nginx

### ISSUE THREAD

**Issue by punkeel** [getupcloud/openshift-nginx-php-fpm#5]
Hi,
i'd like to know if you could update nginx to last version, to solve issues : 
- /var/lib/openshift/<uuid>/nginx-php-fpm//usr/sbin/nginx: error while loading shared libraries: libpcre.so.0: cannot open shared object file: No such file or directory

and
- nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied) 2014/05/10 03:50:44 [alert] 1050#0: version 1.0.15 of nginx.pm is required, but 1.4.7 was found

Precision: I run openshift origin

Thanks in advance :-)

**Comment by caruccio** [comment]
Hi.

Do you have nginx installed at your system?
You can check that with:

```
$ sudo rpm -qa|grep nginx
```

**Comment by punkeel** [comment]
Hi,
yes I do, I think the version is too high ... :-)

```
[root@xxxx]/etc/openshift/plugins.d# sudo rpm -qa|grep nginx
nginx-1.4.7-1.fc19.x86_64
[root@xxxx]/etc/openshift/plugins.d# uname -a
Linux xxxx 3.13.11-100.fc19.x86_64 #1 SMP Wed Apr 23 20:10:57 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by caruccio** [comment]
Hmm, looks like cartridge's usr/bin/nginx is opening the system's nginx.so
I will update the cart so it loads it's own lib. No need to remove your nginx rpm.

Also, you need to install libpcre:

```
$ sudo yum install pcre
```

**Comment by punkeel** [comment]
`pcre-8.32-8.fc19.x86_64` is also installed :-)

Thanks

**Comment by caruccio** [comment]
Could you please try it now?

**Comment by punkeel** [comment]
Still have this error : 
    /var/lib/openshift/536e552f75ecc3ced4000043/nginx-php-fpm//usr/sbin/nginx: error while loading shared libraries: libpcre.so.0: cannot open shared object file: No such file or directory

I solved it the first time by linking the "new"(?) one to the old one ... let's try too

**Comment by caruccio** [comment]
Well, mine is version 7. Maybe if you downgrade....

```
# rpm -qa|grep pcre
pcre-7.8-6.el6.x86_64
```

**Comment by punkeel** [comment]
I had these

```
[root@broker ~]# rpm -qa|grep pcre
pcre-devel-8.32-8.fc19.x86_64
pcre-8.32-8.fc19.x86_64
```

Won't downgrade, too much dependencies ...

```
libpcre.so.1()(64bit) est nécessaire pour (déjà installé) libselinux-2.1.13-15.fc19.x86_64
libpcre.so.1()(64bit) est nécessaire pour (déjà installé) grep-2.14-4.fc19.x86_64
libpcre.so.1()(64bit) est nécessaire pour (déjà installé) libselinux-python-2.1.13-15.fc19.x86_64
libpcre.so.1()(64bit) est nécessaire pour (déjà installé) libselinux-ruby-2.1.13-15.fc19.x86_64
libpcre.so.1()(64bit) est nécessaire pour (déjà installé) mongodb-server-2.4.6-1.fc19.x86_64
libpcre.so.1()(64bit) est nécessaire pour (déjà installé) git-1.8.3.1-1.fc19.x86_64
libpcre.so.1()(64bit) est nécessaire pour (déjà installé) php-cli-5.5.11-1.fc19.x86_64
libpcre.so.1()(64bit) est nécessaire pour (déjà installé) httpd-2.4.9-1.fc19.x86_64
libpcre.so.1()(64bit) est nécessaire pour (déjà installé) php-5.5.11-1.fc19.x86_64
libpcre.so.1()(64bit) est nécessaire pour (déjà installé) qpdf-libs-5.1.1-1.fc19.x86_64
libpcre.so.1()(64bit) est nécessaire pour (déjà installé) mongodb-2.4.6-1.fc19.x86_64
libpcre.so.1()(64bit) est nécessaire pour (déjà installé) haproxy-1.4.24-1.fc19.x86_64
```

Can't you rely on, if present, the system version of nginx ?

**Comment by caruccio** [comment]
I don't think so, because configuration will be somehow broken between versions.

What you could do is to fork this project and update the line https://github.com/getupcloud/openshift-nginx-php-fpm/blob/master/bin/control#L14 so it becomes:

```
/usr/sbin/nginx "$@" >> $OPENSHIFT_PHP_LOG_DIR/nginx_error.log 2>&1
```
