### ISSUE TITLE
PHP 5.5 and the latest nginx?

### ISSUE THREAD

**Issue by pinodex** [getupcloud/openshift-nginx-php-fpm#8]
Is there a way to install PHP 5.5 and the latest version of nginx? Because it installs PHP 5.3 when I use it on my app.

**Comment by caruccio** [comment]
Hi. You can select php version by passing it as parameter `v` on cartridge URL:

```
$ rhc app create phpfpm https://reflector-getupcloud.getup.io/reflect?github=getupcloud/openshift-nginx-php-fpm&v=5.5
```

Regarding nginx version, we are planning to update soon, but it's not a priority right now. In fact, it is really easy to do it yourself. Just compile and update files inside `/versions/shared/usr`.

**Comment by pinodex** [comment]
I see. About the Nginx, I forked this repo and pushed an updated version of Nginx, and it works well.
